[build]
publish = "public"

[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

[context.production.environment]
HUGO_VERSION = "0.111.3"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"
